In [2]:
import pandas as pd

In [22]:
df = pd.read_csv("/SGRNJ06/randd/PROJECT/RD20073101_ScRNA_VDJ/2022_cm/20231007_Huanhuatest/FXT/Mus_0619_PZFXT_2_1X_1T3lib/03.assemble/Mus_0619_PZFXT_2_1X_1T3lib_refine/outs/all_contig_annotations.csv")
df1 = pd.read_csv("/SGRNJ06/randd/PROJECT/RD20073101_ScRNA_VDJ/2022_cm/20231007_Huanhuatest/FXT/Mus_0619_PZFXT_2_1X_1T3lib/03.assemble/Mus_0619_PZFXT_2_1X_1T3lib_refine/outs/filtered_contig_annotations.csv")

In [23]:
df

,barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,...,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id
0,AAACCTGAGAAACCAT-1,True,AAACCTGAGAAACCAT-1_contig_1,True,791,TRA,TRAV5N-4,NaN,TRAJ15,TRAC,...,AAGCAGACCCAAGGACTCATCGTTTTACTGGATAAGAAAGCCAAAC...,CAASPQGGRALIF,TGTGCTGCAAGCCCCCAGGGAGGCAGAGCTCTGATATTT,GTGTTVSVSP,GGAACAGGAACCACGGTATCAGTCAGCCCCA,2471,6,clonotype57,clonotype57_consensus_3,1.0
1,AAACCTGAGAAACCAT-1,True,AAACCTGAGAAACCAT-1_contig_2,True,465,TRB,TRBV13-1,TRBD1,TRBJ1-3,TRBC1,...,CTTCAAATAGGAGATGTCCCTGATGGGTACAAGGCCACCAGAACAA...,CASSEPNQGTGGNTLYF,TGTGCCAGCAGTGAGCCGAACCAGGGGACGGGGGGAAATACGCTCT...,GEGSRLIVV,GGAGAAGGAAGCCGGCTCATTGTTGTAG,23178,40,clonotype57,clonotype57_consensus_1,1.0
2,AAACCTGAGAAACCAT-1,True,AAACCTGAGAAACCAT-1_contig_3,True,456,TRB,TRBV26,NaN,TRBJ2-4,TRBC2,...,CTTCAGCAAATAGACATGACTGAAAAACGATTCTCTGCTGAGTGTC...,CASSNRGSQNTLYF,TGTGCCAGCAGTAACCGGGGGAGTCAAAACACCTTGTACTTT,GAGTRLSVL,GGTGCGGGCACCCGACTATCGGTGCTAG,35488,83,clonotype57,clonotype57_consensus_2,1.0
3,AAACCTGAGAAACCAT-1,True,AAACCTGAGAAACCAT-1_contig_4,True,711,TRA,TRAV13N-4,NaN,TRAJ23,TRAC,...,AAGCAGAGTGGGAGACTGACATCCACAACAGTCATTAAAGAACGTC...,CAMDGNYNQGKLIF,TGTGCTATGGACGGGAATTATAACCAGGGGAAGCTTATCTTT,GQGTKLSIKP,GGACAGGGAACCAAGTTATCTATCAAGCCCA,13363,20,clonotype57,clonotype57_consensus_4,1.0
4,AAACCTGAGAAACCAT-1,True,AAACCTGAGAAACCAT-1_contig_5,True,311,None,NaN,NaN,TRAJ7,TRAC,...,NaN,NaN,NaN,NaN,NaN,371,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14107,AAGGAGCTCTCTTATG-1,True,AAGGAGCTCTCTTATG-1_contig_2,True,437,TRA,TRAV13-1,NaN,TRAJ27,TRAC,...,NaN,CAWDNTNTGKLTF,TGTGCTTGGGATAACACCAATACAGGCAAATTAACCTTT,NaN,NaN,14,1,NaN,NaN,NaN
14108,AAGGCAGAGTAACCCT-1,True,AAGGCAGAGTAACCCT-1_contig_1,True,540,TRB,TRBV3,NaN,TRBJ2-4,TRBC2,...,ATGGAGAAGTCTAAACTGTTTAAGGATCAGTTTTCAGTTGAAAGAC...,CASSLGGRRNTLYF,TGTGCCAGCAGCTTAGGGGGGCGCAGAAACACCTTGTACTTT,GAGTRLSVL,GGTGCGGGCACCCGACTATCGGTGCTAG,102,3,clonotype2908,clonotype2908_consensus_1,1.0
14109,AAGGTTCAGTTACGGG-1,True,AAGGTTCAGTTACGGG-1_contig_1,True,447,TRB,TRBV29,NaN,TRBJ2-1,TRBC2,...,AACAGCGAAGGAGACATCCCTAAAGGATACAGGGTCTCACGGAAGA...,CASSLSGSYAEQFF,TGTGCTAGCAGTTTATCGGGGTCGTATGCTGAGCAGTTCTTC,GPGTRLTVL,GGACCAGGGACACGACTCACCGTCCTAG,84,3,clonotype1951,clonotype1951_consensus_1,1.0
14110,AAGGTTCCAGTGGGAT-1,False,AAGGTTCCAGTGGGAT-1_contig_1,True,652,TRA,TRAV14-3,NaN,TRAJ12,TRAC,...,NaN,CAASWPGTGGYKVVF,TGTGCAGCAAGTTGGCCGGGGACTGGAGGCTATAAAGTGGTCTTT,NaN,NaN,79,3,NaN,NaN,NaN
14111,AATCCAGTCCTCTAGC-1,False,AATCCAGTCCTCTAGC-1_contig_1,False,306,None,NaN,NaN,TRAJ48,TRAC,...,NaN,NaN,NaN,NaN,NaN,14,2,NaN,NaN,NaN

In [24]:
len(set(df.barcode))

5955

In [25]:
len(set(df[(df['productive']==True)&(df['chain'] == "TRA")].barcode))

4012

In [26]:
df = df[df["is_cell"]==True]

In [27]:
len(set(df[(df['productive']==True)&(df['chain'] == "TRA")].barcode))

3909

In [28]:
df[(df['productive']==False)&(df['chain'] == "TRA")]

,barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,...,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id
7,AAACCTGAGAAACCGC-1,True,AAACCTGAGAAACCGC-1_contig_3,True,602,TRA,TRAV7-5,NaN,TRAJ33,TRAC,...,NaN,CTPDSNYQLIW,TGCACCCCGGATAGCAACTATCAGTTGATCTGG,NaN,NaN,2145,3,NaN,NaN,NaN
35,AAACCTGAGAACAATC-1,True,AAACCTGAGAACAATC-1_contig_3,True,333,TRA,TRAV11,NaN,NaN,TRAC,...,NaN,NaN,NaN,NaN,NaN,181,1,NaN,NaN,NaN
63,AAACCTGAGAAGGCCT-1,True,AAACCTGAGAAGGCCT-1_contig_4,True,703,TRA,TRAV7D-2,NaN,TRAJ30,TRAC,...,NaN,CAAQTQMLTK,TGTGCAGCACAGACACAAATGCTTACAAAG,NaN,NaN,3112,4,NaN,NaN,NaN
83,AAACCTGAGAATAGGG-1,True,AAACCTGAGAATAGGG-1_contig_8,True,463,TRA,TRAV4-4-DV10,NaN,TRAJ27,TRAC,...,NaN,CTNTGKLTF,TGCACCAATACAGGCAAATTAACCTTT,NaN,NaN,450,2,NaN,NaN,NaN
94,AAACCTGAGAATTCCC-1,True,AAACCTGAGAATTCCC-1_contig_2,True,695,TRA,TRAV16N,NaN,TRAJ34,TRAC,...,NaN,CYERGSSNTNKVVF,TGCTATGAGAGAGGATCTTCCAATACCAACAAAGTCGTCTTT,NaN,NaN,2448,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14022,AACGTTGCATGGTCTA-1,True,AACGTTGCATGGTCTA-1_contig_2,True,485,TRA,TRAV12-2,NaN,TRAJ42,TRAC,...,NaN,CALSGSGGSNAKLTF,TGTGCTTTGAGTGGGTCTGGAGGAAGCAATGCAAAGCTAACCTTC,NaN,NaN,311,2,NaN,NaN,NaN
14047,AACTCAGCACGGTAGA-1,True,AACTCAGCACGGTAGA-1_contig_2,True,505,TRA,TRAV7D-4,NaN,TRAJ21,NaN,...,NaN,CAASDLMSNYNVLYF,TGTGCAGCTAGTGACCTCATGTCTAATTACAACGTGCTTTACTTC,NaN,NaN,56,2,NaN,NaN,NaN
14055,AACTCAGTCCGTACAA-1,True,AACTCAGTCCGTACAA-1_contig_2,True,459,TRA,TRAV12-2,NaN,TRAJ40,NaN,...,NaN,CAFNTGNYKYVF,TGTGCTTTTAATACAGGAAACTACAAATACGTCTTT,NaN,NaN,10,1,NaN,NaN,NaN
14101,AAGCCGCGTCGAGATG-1,True,AAGCCGCGTCGAGATG-1_contig_2,True,447,TRA,TRAV7-4,NaN,TRAJ37,TRAC,...,NaN,CASSEPGNTGTLIF,TGTGCATCTAGTGAGCCAGGCAATACCGGAACACTCATCTTT,NaN,NaN,7,1,NaN,NaN,NaN
14107,AAGGAGCTCTCTTATG-1,True,AAGGAGCTCTCTTATG-1_contig_2,True,437,TRA,TRAV13-1,NaN,TRAJ27,TRAC,...,NaN,CAWDNTNTGKLTF,TGTGCTTGGGATAACACCAATACAGGCAAATTAACCTTT,NaN,NaN,14,1,NaN,NaN,NaN