In [ ]:
import pandas as pd
import pysam
import matplotlib.pyplot as plt
import pandas as pd
from collections import defaultdict
from Bio.Seq import Seq

In [ ]:
Clonotype	Frequency	IGH_cdr3	IGH_cdr3_nt	contig_id_IGH	IGH_aa	IGH_nt	IGLorK_cdr3	IGLorK_cdr3_nt	contig_id_IGLorKs	IGLorK_aa	IGLorK_nt

In [561]:
out_path = '/SGRNJ06/bioinfo/PROJ04/PROJ_22.10X/P22062202_VDJ/20220712/WCM-20220617-B_BCR/WCM-20220617-B_VDJ_10X/WCM-20220617-B_VDJ_10X/outs'

In [562]:
airr = pd.read_csv(f'{out_path}/airr_rearrangement.tsv',sep='\t')
contig = pd.read_csv(f'{out_path}/filtered_contig_annotations.csv')
clonotype = pd.read_csv(f'{out_path}/clonotypes.csv')

In [563]:
del clonotype['proportion']
clonotype

,clonotype_id,frequency,cdr3s_aa,cdr3s_nt
0,clonotype1,29,IGH:CARSRAMDYW;IGK:CLQYASSPYTF,IGH:TGTGCAAGAAGTCGGGCTATGGACTACTGG;IGK:TGTCTAC...
1,clonotype2,22,IGH:CARFTTVVATYYFDYW;IGH:CARGTTSFDYW;IGH:CARRK...,IGH:TGTGCAAGATTTACTACGGTAGTAGCTACGTACTACTTTGAC...
2,clonotype3,18,IGH:CARSTTVVDDFDYW;IGK:CQQSKEVPRTF,IGH:TGTGCAAGATCTACTACGGTAGTAGATGACTTTGACTACTGG...
3,clonotype4,15,IGH:CARSEDYEGRFAYW;IGK:CQQFTSSPSWTF,IGH:TGTGCAAGATCAGAGGACTACGAAGGCAGGTTTGCTTACTGG...
4,clonotype5,10,IGH:CAREGLLYYW;IGH:CARGTTSFDYW;IGH:CARRKYDADWY...,IGH:TGTGCCAGAGAGGGTCTCCTCTACTACTGG;IGH:TGTGCAA...
...,...,...,...,...
3440,clonotype3441,1,IGH:CTRSPSTMITTGEAMDYW;IGK:CQQWSSYPLTF,IGH:TGTACAAGATCCCCATCTACTATGATTACGACAGGAGAGGCT...
3441,clonotype3442,1,IGH:CARGRDYGSSYARYFDVW;IGK:CQHSRELPFTF,IGH:TGTGCAAGAGGCCGGGACTACGGTAGTAGCTACGCCCGGTAC...
3442,clonotype3443,1,IGH:CARGPNYYGSSYLYAMDYW;IGK:CQQSNSWPLTF,IGH:TGTGCAAGAGGTCCTAATTACTACGGTAGTAGCTACCTCTAT...
3443,clonotype3444,1,IGH:CARGRDYYYYGSSYHWYFDVW;IGK:CQQYSSYPYTF,IGH:TGTGCAAGAGGCCGGGATTATTATTACTACGGTAGTAGCTAC...
3444,clonotype3445,1,IGH:CARHSPRFTTVVATRYYYAMDYW;IGK:CSQSTHVPPTF,IGH:TGTGCAAGACATTCCCCCCGTTTTACTACGGTAGTAGCTACA...

In [564]:
clonotype['cdr3s_aa'] = clonotype['cdr3s_aa'].apply(lambda x:x.split(';'))
clonotype['cdr3s_nt'] = clonotype['cdr3s_nt'].apply(lambda x:x.split(';'))

In [565]:
clonotype

,clonotype_id,frequency,cdr3s_aa,cdr3s_nt
0,clonotype1,29,"[IGH:CARSRAMDYW, IGK:CLQYASSPYTF]","[IGH:TGTGCAAGAAGTCGGGCTATGGACTACTGG, IGK:TGTCT..."
1,clonotype2,22,"[IGH:CARFTTVVATYYFDYW, IGH:CARGTTSFDYW, IGH:CA...",[IGH:TGTGCAAGATTTACTACGGTAGTAGCTACGTACTACTTTGA...
2,clonotype3,18,"[IGH:CARSTTVVDDFDYW, IGK:CQQSKEVPRTF]",[IGH:TGTGCAAGATCTACTACGGTAGTAGATGACTTTGACTACTG...
3,clonotype4,15,"[IGH:CARSEDYEGRFAYW, IGK:CQQFTSSPSWTF]",[IGH:TGTGCAAGATCAGAGGACTACGAAGGCAGGTTTGCTTACTG...
4,clonotype5,10,"[IGH:CAREGLLYYW, IGH:CARGTTSFDYW, IGH:CARRKYDA...","[IGH:TGTGCCAGAGAGGGTCTCCTCTACTACTGG, IGH:TGTGC..."
...,...,...,...,...
3440,clonotype3441,1,"[IGH:CTRSPSTMITTGEAMDYW, IGK:CQQWSSYPLTF]",[IGH:TGTACAAGATCCCCATCTACTATGATTACGACAGGAGAGGC...
3441,clonotype3442,1,"[IGH:CARGRDYGSSYARYFDVW, IGK:CQHSRELPFTF]",[IGH:TGTGCAAGAGGCCGGGACTACGGTAGTAGCTACGCCCGGTA...
3442,clonotype3443,1,"[IGH:CARGPNYYGSSYLYAMDYW, IGK:CQQSNSWPLTF]",[IGH:TGTGCAAGAGGTCCTAATTACTACGGTAGTAGCTACCTCTA...
3443,clonotype3444,1,"[IGH:CARGRDYYYYGSSYHWYFDVW, IGK:CQQYSSYPYTF]",[IGH:TGTGCAAGAGGCCGGGATTATTATTACTACGGTAGTAGCTA...
3444,clonotype3445,1,"[IGH:CARHSPRFTTVVATRYYYAMDYW, IGK:CSQSTHVPPTF]",[IGH:TGTGCAAGACATTCCCCCCGTTTTACTACGGTAGTAGCTAC...

In [566]:
aa_list = clonotype['cdr3s_aa'].tolist()
aa_dict = {}
for i,j in enumerate(aa_list,1):
    aa_dict[i] = j

In [574]:
aa_dict[3444]

['IGH:CARGRDYYYYGSSYHWYFDVW', 'IGK:CQQYSSYPYTF']

In [575]:
IGH_cdr3 = dict()
IGL_cdr3 = dict()

In [576]:
for key,value in aa_dict.items():
    if len(value)==2: 
        for i in value:
            if i.startswith('IGH'):
                IGH_cdr3['clonotype'+str(key)]= (i.split(':')[-1])
            else:
                IGL_cdr3['clonotype'+str(key)]= (i.split(':')[-1])

In [ ]:
IGH_cdr3

In [578]:
df_IGH_cdr3 = pd.DataFrame(list(IGH_cdr3.items()),columns=['clonotype_id', 'IGH_cdr3'])
df_IGL_cdr3 = pd.DataFrame(list(IGL_cdr3.items()),columns=['clonotype_id', 'IGLorK_cdr3'])

In [579]:
df_merge = pd.merge(clonotype,df_IGH_cdr3,on='clonotype_id',how='inner')
df_merge = pd.merge(df_merge, df_IGL_cdr3,on='clonotype_id',how='inner')

In [580]:
del df_merge['cdr3s_aa']

In [581]:
df_merge

,clonotype_id,frequency,cdr3s_nt,IGH_cdr3,IGLorK_cdr3
0,clonotype1,29,"[IGH:TGTGCAAGAAGTCGGGCTATGGACTACTGG, IGK:TGTCT...",CARSRAMDYW,CLQYASSPYTF
1,clonotype3,18,[IGH:TGTGCAAGATCTACTACGGTAGTAGATGACTTTGACTACTG...,CARSTTVVDDFDYW,CQQSKEVPRTF
2,clonotype4,15,[IGH:TGTGCAAGATCAGAGGACTACGAAGGCAGGTTTGCTTACTG...,CARSEDYEGRFAYW,CQQFTSSPSWTF
3,clonotype6,9,[IGH:TGTGCAAGAAGGAGGGGGATCTACTATGATTACGACGGGTT...,CARRRGIYYDYDGFAYW,CQNDYSYPLTF
4,clonotype7,8,"[IGH:TGTACCCTTAACTGGGACGGGTTTGCTTACTGG, IGK:TG...",CTLNWDGFAYW,CSQSTHVPWTF
...,...,...,...,...,...
2673,clonotype3441,1,[IGH:TGTACAAGATCCCCATCTACTATGATTACGACAGGAGAGGC...,CTRSPSTMITTGEAMDYW,CQQWSSYPLTF
2674,clonotype3442,1,[IGH:TGTGCAAGAGGCCGGGACTACGGTAGTAGCTACGCCCGGTA...,CARGRDYGSSYARYFDVW,CQHSRELPFTF
2675,clonotype3443,1,[IGH:TGTGCAAGAGGTCCTAATTACTACGGTAGTAGCTACCTCTA...,CARGPNYYGSSYLYAMDYW,CQQSNSWPLTF
2676,clonotype3444,1,[IGH:TGTGCAAGAGGCCGGGATTATTATTACTACGGTAGTAGCTA...,CARGRDYYYYGSSYHWYFDVW,CQQYSSYPYTF
2677,clonotype3445,1,[IGH:TGTGCAAGACATTCCCCCCGTTTTACTACGGTAGTAGCTAC...,CARHSPRFTTVVATRYYYAMDYW,CSQSTHVPPTF

In [582]:
nt_list = clonotype['cdr3s_nt'].tolist()
nt_dict = {}
for i,j in enumerate(nt_list,1):
    nt_dict[i] = j

In [583]:
IGH_cdr3_nt = dict()
IGL_cdr3_nt = dict()

In [584]:
for key,value in nt_dict.items():
    for i in value:
        if i.startswith('IGH'):
            IGH_cdr3_nt['clonotype'+str(key)]=(i.split(':')[-1])
        else:
            IGL_cdr3_nt['clonotype'+str(key)]=(i.split(':')[-1])

In [585]:
df_IGH_cdr3_nt = pd.DataFrame(list(IGH_cdr3_nt.items()),columns=['clonotype_id', 'IGH_cdr3_nt'])
df_IGL_cdr3_nt = pd.DataFrame(list(IGL_cdr3_nt.items()),columns=['clonotype_id', 'IGLorK_cdr3_nt'])

In [586]:
df_merge = pd.merge(df_merge,df_IGH_cdr3_nt,on='clonotype_id',how='inner')
df_merge = pd.merge(df_merge,df_IGL_cdr3_nt,on='clonotype_id',how='inner')

In [587]:
del df_merge['cdr3s_nt']
df_merge

,clonotype_id,frequency,IGH_cdr3,IGLorK_cdr3,IGH_cdr3_nt,IGLorK_cdr3_nt
0,clonotype1,29,CARSRAMDYW,CLQYASSPYTF,TGTGCAAGAAGTCGGGCTATGGACTACTGG,TGTCTACAATATGCTAGTTCTCCGTACACGTTC
1,clonotype3,18,CARSTTVVDDFDYW,CQQSKEVPRTF,TGTGCAAGATCTACTACGGTAGTAGATGACTTTGACTACTGG,TGTCAGCAAAGTAAGGAGGTTCCTCGGACGTTC
2,clonotype4,15,CARSEDYEGRFAYW,CQQFTSSPSWTF,TGTGCAAGATCAGAGGACTACGAAGGCAGGTTTGCTTACTGG,TGCCAGCAGTTTACTAGTTCCCCATCGTGGACGTTC
3,clonotype6,9,CARRRGIYYDYDGFAYW,CQNDYSYPLTF,TGTGCAAGAAGGAGGGGGATCTACTATGATTACGACGGGTTTGCTT...,TGTCAGAATGATTATAGTTATCCGCTCACGTTC
4,clonotype7,8,CTLNWDGFAYW,CSQSTHVPWTF,TGTACCCTTAACTGGGACGGGTTTGCTTACTGG,TGCTCTCAAAGTACACATGTTCCGTGGACGTTC
...,...,...,...,...,...,...
2673,clonotype3441,1,CTRSPSTMITTGEAMDYW,CQQWSSYPLTF,TGTACAAGATCCCCATCTACTATGATTACGACAGGAGAGGCTATGG...,TGCCAGCAGTGGAGTAGTTACCCGCTCACGTTC
2674,clonotype3442,1,CARGRDYGSSYARYFDVW,CQHSRELPFTF,TGTGCAAGAGGCCGGGACTACGGTAGTAGCTACGCCCGGTACTTCG...,TGTCAGCACAGTAGGGAGCTTCCATTCACGTTC
2675,clonotype3443,1,CARGPNYYGSSYLYAMDYW,CQQSNSWPLTF,TGTGCAAGAGGTCCTAATTACTACGGTAGTAGCTACCTCTATGCTA...,TGTCAACAGAGTAACAGCTGGCCGCTCACGTTC
2676,clonotype3444,1,CARGRDYYYYGSSYHWYFDVW,CQQYSSYPYTF,TGTGCAAGAGGCCGGGATTATTATTACTACGGTAGTAGCTACCACT...,TGTCAGCAATATAGCAGCTATCCGTACACGTTC
2677,clonotype3445,1,CARHSPRFTTVVATRYYYAMDYW,CSQSTHVPPTF,TGTGCAAGACATTCCCCCCGTTTTACTACGGTAGTAGCTACACGGT...,TGCTCTCAAAGTACACATGTTCCTCCCACGTTC

In [588]:
df_merge['Clonotype'] = df_merge['IGH_cdr3'] + '_' + df_merge['IGLorK_cdr3']

In [589]:
df_merge =df_merge[['clonotype_id','Clonotype','frequency','IGH_cdr3','IGH_cdr3_nt','IGLorK_cdr3','IGLorK_cdr3_nt']]

In [590]:
df_merge

,clonotype_id,Clonotype,frequency,IGH_cdr3,IGH_cdr3_nt,IGLorK_cdr3,IGLorK_cdr3_nt
0,clonotype1,CARSRAMDYW_CLQYASSPYTF,29,CARSRAMDYW,TGTGCAAGAAGTCGGGCTATGGACTACTGG,CLQYASSPYTF,TGTCTACAATATGCTAGTTCTCCGTACACGTTC
1,clonotype3,CARSTTVVDDFDYW_CQQSKEVPRTF,18,CARSTTVVDDFDYW,TGTGCAAGATCTACTACGGTAGTAGATGACTTTGACTACTGG,CQQSKEVPRTF,TGTCAGCAAAGTAAGGAGGTTCCTCGGACGTTC
2,clonotype4,CARSEDYEGRFAYW_CQQFTSSPSWTF,15,CARSEDYEGRFAYW,TGTGCAAGATCAGAGGACTACGAAGGCAGGTTTGCTTACTGG,CQQFTSSPSWTF,TGCCAGCAGTTTACTAGTTCCCCATCGTGGACGTTC
3,clonotype6,CARRRGIYYDYDGFAYW_CQNDYSYPLTF,9,CARRRGIYYDYDGFAYW,TGTGCAAGAAGGAGGGGGATCTACTATGATTACGACGGGTTTGCTT...,CQNDYSYPLTF,TGTCAGAATGATTATAGTTATCCGCTCACGTTC
4,clonotype7,CTLNWDGFAYW_CSQSTHVPWTF,8,CTLNWDGFAYW,TGTACCCTTAACTGGGACGGGTTTGCTTACTGG,CSQSTHVPWTF,TGCTCTCAAAGTACACATGTTCCGTGGACGTTC
...,...,...,...,...,...,...,...
2673,clonotype3441,CTRSPSTMITTGEAMDYW_CQQWSSYPLTF,1,CTRSPSTMITTGEAMDYW,TGTACAAGATCCCCATCTACTATGATTACGACAGGAGAGGCTATGG...,CQQWSSYPLTF,TGCCAGCAGTGGAGTAGTTACCCGCTCACGTTC
2674,clonotype3442,CARGRDYGSSYARYFDVW_CQHSRELPFTF,1,CARGRDYGSSYARYFDVW,TGTGCAAGAGGCCGGGACTACGGTAGTAGCTACGCCCGGTACTTCG...,CQHSRELPFTF,TGTCAGCACAGTAGGGAGCTTCCATTCACGTTC
2675,clonotype3443,CARGPNYYGSSYLYAMDYW_CQQSNSWPLTF,1,CARGPNYYGSSYLYAMDYW,TGTGCAAGAGGTCCTAATTACTACGGTAGTAGCTACCTCTATGCTA...,CQQSNSWPLTF,TGTCAACAGAGTAACAGCTGGCCGCTCACGTTC
2676,clonotype3444,CARGRDYYYYGSSYHWYFDVW_CQQYSSYPYTF,1,CARGRDYYYYGSSYHWYFDVW,TGTGCAAGAGGCCGGGATTATTATTACTACGGTAGTAGCTACCACT...,CQQYSSYPYTF,TGTCAGCAATATAGCAGCTATCCGTACACGTTC
2677,clonotype3445,CARHSPRFTTVVATRYYYAMDYW_CSQSTHVPPTF,1,CARHSPRFTTVVATRYYYAMDYW,TGTGCAAGACATTCCCCCCGTTTTACTACGGTAGTAGCTACACGGT...,CSQSTHVPPTF,TGCTCTCAAAGTACACATGTTCCTCCCACGTTC

In [ ]:
airr

In [ ]:
airr = airr[['clone_id','sequence_id','sequence','sequence_aa']]

In [ ]:
airr.rename(columns={'sequence_id':'contig_id'},inplace=True)

In [ ]:
contig.sort_values('reads',ascending=False,inplace=True)

In [ ]:
contig= contig[['contig_id','chain']]

In [ ]:
df_merge1 = pd.merge(airr,contig,on='contig_id')

In [ ]:
df_merge1.rename(columns={'clone_id':'clonotype_id'},inplace=True)

In [ ]:
df_merge1['idnum'] = df_merge1['clonotype_id'].apply(lambda x: int(x[9:]))

In [ ]:
df_merge1.sort_values(['idnum','chain'],inplace=True)

In [ ]:
del df_merge1['idnum']

In [ ]:
df_merge1

In [ ]:
target_contigid = df_merge['clonotype_id'].tolist()

In [ ]:
df_merge1 = df_merge1[df_merge1['clonotype_id'].isin(target_contigid)]

In [ ]:
df_merge1

In [ ]:
df_merge1.drop_duplicates(['clonotype_id','chain'],inplace=True)
# df_merge1 = df_merge1.where(df_merge_f.notnull(),'None')

In [ ]:
df_merge1

In [ ]:
df_merge

In [ ]:
df_merge1_IGH = df_merge1[df_merge1['chain']=='IGH']
df_merge1_IGL = df_merge1[df_merge1['chain']!='IGH']

In [ ]:
del df_merge1_IGH['chain']
del df_merge1_IGL['chain']
df_merge1_IGH.rename(columns={'contig_id':'contig_id_IGH'},inplace=True)
df_merge1_IGL.rename(columns={'contig_id':'contig_id_IGLorKs'},inplace=True)

In [ ]:
df_merge1_IGH.rename(columns={'sequence':'IGH_nt'},inplace=True)
df_merge1_IGL.rename(columns={'sequence':'IGLorK_nt'},inplace=True)
df_merge1_IGH.rename(columns={'sequence_aa':'IGH_aa'},inplace=True)
df_merge1_IGL.rename(columns={'sequence_aa':'IGLorK_aa'},inplace=True)

In [ ]:
df_merge1_IGH

In [ ]:
df_merge_f = pd.merge(df_merge,df_merge1_IGH,on='clonotype_id')

In [ ]:
df_merge_f = pd.merge(df_merge_f,df_merge1_IGL,on='clonotype_id')

In [ ]:
df_merge_f

In [ ]:
df_merge_f.columns

In [ ]:
df_merge_f.rename(columns={'frequency':'Frequency'},inplace=True)

In [ ]:
df_merge_f = df_merge_f[['clonotype_id','Clonotype','Frequency','IGH_cdr3','IGH_cdr3_nt','contig_id_IGH','IGH_aa','IGH_nt',
                        'IGLorK_cdr3','IGLorK_cdr3_nt','contig_id_IGLorKs','IGLorK_aa','IGLorK_nt']]

In [ ]:
df_merge_f

In [ ]:
df_merge_f.to_csv('/SGRNJ06/randd/USER/cjj/celedev/vdj10x/20220725anno_seq_suzhou/filtered_contig_annotations_pair_productive_with_sequence.tsv',sep='\t')